language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 2.0.0

## If `dotnet` configuration doesnt work, use install script instead
# install:
#  - export DOTNET_INSTALL_DIR="$PWD/.dotnetsdk"
#  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
#  - export PATH="$DOTNET_INSTALL_DIR:$PATH"  

script:
  - dotnet --info
  - dotnet --version
  - dotnet run
  - ls -a
  
#after_script:
#  - dotnet publish --output publish
#  - cd publish
#  - git init
#  - git config user.name "${U_NAME}"
#  - git config user.email "${U_EMAIL}"
#  - git add .
#  - git commit -m "publish"
#  - git remote add githuborigin "https://${GH_TOKEN}@${GH_REF}"
#  - git push --force --quiet githuborigin master:${P_BRANCH}

branches:
  only:
    - master